services:
  _defaults:
    public: false
    autowire: true

  Dl\StarWarsBundle\DataAccess\DoctrineRepositoryFactory:
    class: DL\StarWarsBundle\DataAccess\DoctrineRepositoryFactory

  Dl\StarWarsBundle\DataAccess\CharacterSwapiDal:
    class: DL\StarWarsBundle\DataAccess\CharacterSwapiDal

  DL\StarWarsBundle\DataAccess\CharacterDoctrineDal:
    class: DL\StarWarsBundle\DataAccess\CharacterDoctrineDal
    factory:
      - "@Dl\\StarWarsBundle\\DataAccess\\DoctrineRepositoryFactory"
      - "create"
    arguments:
      - "DLStarWarsBundle:CharacterDto"
